version: "3.8"

services:
  postgres:
    image: postgres:13.0
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=public
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    command: redis-server
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/var/lib/redis


volumes: 
  postgres: {}
  redis: {}