version: "3.8"

services:
  postgres:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=public
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    command: redis-server
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/var/lib/redis

  sharechat:
    depends_on:
      - postgres
      - redis
    build: . 
    command: [
      "--allowed-origin", 
      "*",
    ]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASS: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_NAME: public
      REDIS_USER: ""
      REDIS_PASS: ""
      REDIS_HOST: redis:6379
    ports:
      - 8080:8080


volumes: 
  postgres: {}
  redis: {}
